/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry.manager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Baskoro Adi
 */
public class CucianMasuk extends javax.swing.JFrame {

    /**
     * Creates new form SetorLaundry
     */
    Connection conn = Koneksi.getConnection();
    private DefaultTableModel model;

    public CucianMasuk() {

        initComponents();
        setTitle("Transaksi Laundry");
        model = new DefaultTableModel(
                new String[]{"ID Customer", "ID Laundry", "Nama", "No HP", "Alamat", "JK",
                    "Berat (kg)", "Penerimaan Barang (date)", "Harga", "Status Bayar",
                    "Status Transaksi", "Selesai (date)"}, 0);
        jTable_CucianMasuk.setModel(model);
        label_namaAdmin.setText(String.valueOf(adm.nameAdm));
        setLocationRelativeTo(null);
        tanggalNow();
        tampil();
    }

    private void tanggalNow() {
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        date_masuk.setDateFormatString("dd/MM/yyyy");
        date_masuk.setDate(date);
    }

    private void tampil() {
        try {
            model.setRowCount(0); // clear the table
            String query = "SELECT * FROM cucian JOIN pelanggan ON cucian.id_pelanggan = pelanggan.id_pelanggan";
            Statement statement = conn.createStatement();
            ResultSet result = statement.executeQuery(query);
            if (!result.next()) {
                JOptionPane.showMessageDialog(this, "No data found!", "Notification", JOptionPane.WARNING_MESSAGE);
            } else {
                do {
                    Object[] row = {
                        result.getString("id_pelanggan"),
                        result.getString("id_cucian"),
                        result.getString("nama_pelanggan"),
                        result.getString("nomer_hp"),
                        result.getString("alamat_pelanggan"),
                        result.getString("jenis_kelamin"),
                        result.getInt("berat"),
                        result.getString("tanggal_masuk"),
                        result.getInt("harga"),
                        result.getString("statuspembayaran"),
                        result.getString("statustransaksi"),
                        result.getString("tanggal_keluar")
                    };
                    model.addRow(row);
                } while (result.next());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void reset() {
        txt_Nama.setText("");
        txt_Alamat.setText("");
        txt_NoHP.setText("");
        jk.clearSelection();
        txt_Berat.setText("");
        txt_Harga.setText("");
        ComboStatusBayar.setSelectedItem("Belum Lunas");
        ComboStatusTransaksi.setSelectedItem("On Process");
    }

    private int calculatePrice(int weight) {
        int pricePerKg = 5000;
        return weight * pricePerKg;
    }

    private boolean deleteCucianById(int cucianId) {
        String deleteCucianQuery = "DELETE FROM cucian WHERE id_cucian=?";
        try ( PreparedStatement statement = conn.prepareStatement(deleteCucianQuery)) {
            statement.setInt(1, cucianId);
            statement.executeUpdate();
            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jk = new javax.swing.ButtonGroup();
        label_namaAdmin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Alamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_NoHP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton_Laki = new javax.swing.JRadioButton();
        jRadioButton_Perempuan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Berat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        date_masuk = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jButton_Hitung = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Simpan = new javax.swing.JButton();
        txt_Harga = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        ComboStatusBayar = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ComboStatusTransaksi = new javax.swing.JComboBox<>();
        jButton_Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_CucianMasuk = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        label_namaAdmin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Laundry Data");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Pelanggan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nomer HP");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");

        jk.add(jRadioButton_Laki);
        jRadioButton_Laki.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_Laki.setText("Male");

        jk.add(jRadioButton_Perempuan);
        jRadioButton_Perempuan.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_Perempuan.setText("Female");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data Cucian");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Berat (Kg)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total (Rp)");

        jButton_Hitung.setText("Total");
        jButton_Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HitungActionPerformed(evt);
            }
        });

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Simpan.setText("Tambah");
        jButton_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SimpanActionPerformed(evt);
            }
        });

        txt_Harga.setEditable(false);
        txt_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HargaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status Pembayaran");

        ComboStatusBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Lunas", "Lunas" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Keterangan");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status Transaksi");

        ComboStatusTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On Process", "Selesai" }));

        jButton_Back.setText("Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jTable_CucianMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_CucianMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CucianMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_CucianMasuk);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Delete)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Update)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Simpan))
                    .addComponent(jSeparator3)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Back))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(47, 47, 47)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_Nama)
                                                .addComponent(txt_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel3))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_Berat))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(48, 48, 48)
                                        .addComponent(date_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9))
                                            .addGap(18, 18, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ComboStatusTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ComboStatusBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton_Laki)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_Perempuan))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(30, 30, 30)
                                        .addComponent(txt_NoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_Hitung)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(ComboStatusTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(ComboStatusBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_Berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_masuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton_Laki)
                    .addComponent(jRadioButton_Perempuan)
                    .addComponent(jButton_Hitung))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Simpan)
                    .addComponent(jButton_Delete)
                    .addComponent(jButton_Update))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jButton_Back)
                .addContainerGap())
        );

        jMenu1.setText("Auth");

        jMenuItem1.setText("Customer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Admin");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laundry");

        jMenuItem3.setText("Transaksi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Report ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jMenuItem5.setText("Credit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(857, Short.MAX_VALUE)
                .addComponent(label_namaAdmin)
                .addGap(193, 193, 193))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_namaAdmin))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        new Homepage().show();
        this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HitungActionPerformed
        try {
            String weightString = txt_Berat.getText();
            if (weightString.length() == 0) {
                JOptionPane.showMessageDialog(this, "Isi berat terlebih dahulu!", "Notification", JOptionPane.WARNING_MESSAGE);
            } else {
                int weight = Integer.parseInt(weightString);
                int price = calculatePrice(weight);

                String priceString = String.valueOf(price);
                txt_Harga.setText(priceString);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Inputan harus angka!", "Notification", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_HitungActionPerformed

    private void jButton_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SimpanActionPerformed

        if (adm.idAdmin == 0) {
            JOptionPane.showMessageDialog(this, "Anda belum login!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (txt_Nama.getText().isBlank() || txt_Alamat.getText().isBlank() || txt_NoHP.getText().isBlank() || txt_Harga.getText().isBlank() || txt_Berat.getText().isBlank() || jk.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!", "Notification", JOptionPane.WARNING_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String strdate = dateFormat.format(date_masuk.getDate());
            String nama = txt_Nama.getText();
            String alamat = txt_Alamat.getText();
            String noHp = txt_NoHP.getText();
            String jenisKelamin = jRadioButton_Laki.isSelected() ? "Laki-Laki" : "Perempuan";
            int berat = Integer.parseInt(txt_Berat.getText());
            int harga = Integer.parseInt(txt_Harga.getText());
            String statusbayar = ComboStatusBayar.getSelectedItem().toString();
            String statustransaksi = ComboStatusTransaksi.getSelectedItem().toString();
            try {
                String query = "INSERT INTO pelanggan(nama_pelanggan, alamat_pelanggan, nomer_hp, jenis_kelamin) VALUES(?,?,?,?)";
                PreparedStatement statement = (PreparedStatement) conn.prepareStatement(query);
                statement.setString(1, nama);
                statement.setString(2, alamat);
                statement.setString(3, noHp);
                statement.setString(4, jenisKelamin);
                statement.executeUpdate();

                String query2 = "INSERT INTO cucian(berat, tanggal_masuk, harga, statuspembayaran, statustransaksi, id_pelanggan, id_admin) VALUES(?,?,?,?,?,?,?)";
                PreparedStatement statement2 = (PreparedStatement) conn.prepareStatement(query2);
                statement2.setInt(1, berat);
                statement2.setString(2, strdate);
                statement2.setInt(3, harga);
                statement2.setString(4, statusbayar);
                statement2.setString(5, statustransaksi);
                statement2.setInt(6, adm.fixId + 1);
                statement2.setInt(7, adm.idAdmin);
                statement2.executeUpdate();
                JOptionPane.showMessageDialog(this, "Berhasil Menambahkan!", "Success", JOptionPane.PLAIN_MESSAGE);
                tampil();
                reset();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Gagal Menambahkan! " + ex, "Failed", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton_SimpanActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed

        if (jTable_CucianMasuk.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tabel Kosong!", "Notification", JOptionPane.WARNING_MESSAGE);
        } else if (jTable_CucianMasuk.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Pilih Data yang Akan Dihapus!", "Notification", JOptionPane.WARNING_MESSAGE);
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin Ingin Menghapus?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                int cucianIdToDelete = Integer.parseInt(model.getValueAt(jTable_CucianMasuk.getSelectedRow(), 1).toString());
                if (deleteCucianById(cucianIdToDelete)) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!", "Success", JOptionPane.PLAIN_MESSAGE);
                    tampil();
                    reset();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal Menghapus Data!", "Failed", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jTable_CucianMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CucianMasukMouseClicked

        int selectedRow = jTable_CucianMasuk.getSelectedRow();
        if (selectedRow != -1) {
            txt_Nama.setText(model.getValueAt(selectedRow, 2).toString());
            txt_NoHP.setText(model.getValueAt(selectedRow, 3).toString());
            txt_Alamat.setText(model.getValueAt(selectedRow, 4).toString());
            String jk = model.getValueAt(selectedRow, 5).toString();
            jRadioButton_Laki.setSelected(jk.equalsIgnoreCase("laki-laki"));
            jRadioButton_Perempuan.setSelected(jk.equalsIgnoreCase("perempuan"));
            txt_Berat.setText(model.getValueAt(selectedRow, 6).toString());
            try {
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                Date createDate = df.parse(model.getValueAt(selectedRow, 7).toString());
                date_masuk.setDate(createDate);
            } catch (ParseException e) {
                System.out.println(e);
            }
            txt_Harga.setText(model.getValueAt(selectedRow, 8).toString());
            ComboStatusBayar.setSelectedItem(model.getValueAt(selectedRow, 9));
            ComboStatusTransaksi.setSelectedItem(model.getValueAt(selectedRow, 10));
        }


    }//GEN-LAST:event_jTable_CucianMasukMouseClicked

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        date_masuk.setDateFormatString("dd/MM/yyyy");

        if (jTable_CucianMasuk.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please fill all require fields!", "Notification", JOptionPane.WARNING_MESSAGE);
        } else if (jTable_CucianMasuk.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Select the data you want to change first!", "Notification", JOptionPane.WARNING_MESSAGE);
        } else if (ComboStatusBayar.getSelectedItem() == "Not yet paid off" && ComboStatusTransaksi.getSelectedItem() == "Selesai") {
            JOptionPane.showMessageDialog(this, "Please complete pay first", "Notification", JOptionPane.WARNING_MESSAGE);
        } else if (ComboStatusBayar.getSelectedItem() == "Lunas" && ComboStatusTransaksi.getSelectedItem() == "Selesai") {
            String id_cuci = model.getValueAt(jTable_CucianMasuk.getSelectedRow(), 1).toString();
            String id_pelanggan = model.getValueAt(jTable_CucianMasuk.getSelectedRow(), 0).toString();
            String nama = txt_Nama.getText();
            String strdate = dateFormat.format(date_masuk.getDate());
            String alamat = txt_Alamat.getText();
            String noHp = txt_NoHP.getText();
            String jenisKelamin = null;
            String weight = txt_Berat.getText();
            int berat = Integer.parseInt(weight);
            String cost = txt_Harga.getText();
            int harga = Integer.parseInt(cost);
            if (jRadioButton_Laki.isSelected()) {
                jenisKelamin = "Laki-Laki";
            } else if (jRadioButton_Perempuan.isSelected()) {
                jenisKelamin = "Perempuan";
            }
            String statusbayar = ComboStatusBayar.getSelectedItem().toString();
            String statustransaksi = ComboStatusTransaksi.getSelectedItem().toString();
            Date date = new Date();
            String tanggalNow = dateFormat.format(date);
            String sql = "UPDATE pelanggan SET nama_pelanggan=?,alamat_pelanggan=?,nomer_hp=?,jenis_kelamin=? WHERE id_pelanggan =?";
            String sql2 = "UPDATE cucian SET berat=?,tanggal_masuk=?,harga=?,statuspembayaran=?,statustransaksi=?,tanggal_keluar=? WHERE id_cucian=?";
            try {
                PreparedStatement statement = (PreparedStatement) conn.prepareStatement(sql);
                statement.setString(1, nama);
                statement.setString(2, alamat);
                statement.setString(3, noHp);
                statement.setString(4, jenisKelamin);
                statement.setString(5, id_pelanggan);

                PreparedStatement statement2 = (PreparedStatement) conn.prepareStatement(sql2);
                statement2.setInt(1, berat);
                statement2.setString(2, strdate);
                statement2.setInt(3, harga);
                statement2.setString(4, statusbayar);
                statement2.setString(5, statustransaksi);
//                statement2.setString(6, tanggalNow);
                statement2.setString(6, tanggalNow);
                statement2.setString(7, id_cuci);

                statement.executeUpdate();
                statement2.executeUpdate();
                JOptionPane.showMessageDialog(this, "Berhasil Update!", "Success", JOptionPane.PLAIN_MESSAGE);
                reset();
                tampil();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal Update! " + e, "Failed", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            String id_cuci = model.getValueAt(jTable_CucianMasuk.getSelectedRow(), 1).toString();
            String id_pelanggan = model.getValueAt(jTable_CucianMasuk.getSelectedRow(), 0).toString();
            String nama = txt_Nama.getText();
            String strdate = dateFormat.format(date_masuk.getDate());
            String alamat = txt_Alamat.getText();
            String noHp = txt_NoHP.getText();
            String jenisKelamin = null;
            String weight = txt_Berat.getText();
            int berat = Integer.parseInt(weight);
            String cost = txt_Harga.getText();
            int harga = Integer.parseInt(cost);
            if (jRadioButton_Laki.isSelected()) {
                jenisKelamin = "Laki-Laki";
            } else if (jRadioButton_Perempuan.isSelected()) {
                jenisKelamin = "Perempuan";
            }
            String statusbayar = ComboStatusBayar.getSelectedItem().toString();
            String statustransaksi = ComboStatusTransaksi.getSelectedItem().toString();
            String sql = "UPDATE pelanggan SET nama_pelanggan=?,alamat_pelanggan=?,nomer_hp=?,jenis_kelamin=? WHERE id_pelanggan =?";
            String sql2 = "UPDATE cucian SET berat=?,tanggal_masuk=?,harga=?,statuspembayaran=?,statustransaksi=? WHERE id_cucian=?";
            try {
                PreparedStatement statement = (PreparedStatement) conn.prepareStatement(sql);
                statement.setString(1, nama);
                statement.setString(2, alamat);
                statement.setString(3, noHp);
                statement.setString(4, jenisKelamin);
                statement.setString(5, id_pelanggan);

                PreparedStatement statement2 = (PreparedStatement) conn.prepareStatement(sql2);
                statement2.setInt(1, berat);
                statement2.setString(2, strdate);
                statement2.setInt(3, harga);
                statement2.setString(4, statusbayar);
                statement2.setString(5, statustransaksi);
                statement2.setString(6, id_cuci);

                statement.executeUpdate();
                statement2.executeUpdate();
                reset();
                tampil();
                JOptionPane.showMessageDialog(this, "Berhasil Update!", "Success", JOptionPane.PLAIN_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal Update! " + e, "Failed", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void txt_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HargaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new LaporanTransaksi().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Pelanggan().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Admin().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new CucianMasuk().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(this, "Farhan Ali Ramadhan" + "\n" + "001202200044" + "\n" + " Information Technology", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CucianMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CucianMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CucianMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CucianMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CucianMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboStatusBayar;
    private javax.swing.JComboBox<String> ComboStatusTransaksi;
    private com.toedter.calendar.JDateChooser date_masuk;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Hitung;
    private javax.swing.JButton jButton_Simpan;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton_Laki;
    private javax.swing.JRadioButton jRadioButton_Perempuan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable_CucianMasuk;
    private javax.swing.ButtonGroup jk;
    private javax.swing.JLabel label_namaAdmin;
    private javax.swing.JTextField txt_Alamat;
    private javax.swing.JTextField txt_Berat;
    private javax.swing.JTextField txt_Harga;
    private javax.swing.JTextField txt_Nama;
    private javax.swing.JTextField txt_NoHP;
    // End of variables declaration//GEN-END:variables
}
